name: build

on:
  workflow_dispatch:
  push:
      branches:
      - main
    
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: build 
          run: |
            npm install vite
            npm run build
        
        - name: deploy
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist